coverage:
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 10%
        paths: 
          - "src"
comment:                
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false 
  require_base: no 
  require_head: yes 
  branches:
    - "master"
