name: Publish Packages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish EventSourced
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/EventSourced/EventSourced.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          VERSION_STATIC: 0.1-alpha
    - name: Publish EventSourced.Persistence.InMemory
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/EventSourced.Persistence.InMemory/EventSourced.Persistence.InMemory.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          VERSION_STATIC: 0.1-alpha
    - name: Publish EventSourced.Persistence.EntityFramework
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/EventSourced.Persistence.EntityFramework/EventSourced.Persistence.EntityFramework.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUGET_SOURCE: https://api.nuget.org
        VERSION_STATIC: 0.1-alpha
    - name: Publish EventSourced.Diagnostics.Web
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/EventSourced.Diagnostics.Web/EventSourced.Diagnostics.Web.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUGET_SOURCE: https://api.nuget.org
        VERSION_STATIC: 0.1-alpha
    - name: Publish EventSourced.ExternalEvents.API
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/EventSourced.ExternalEvents.API/EventSourced.ExternalEvents.API.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUGET_SOURCE: https://api.nuget.org
        VERSION_STATIC: 0.1-alpha

